


<P ID="1">A chronological look at mad cow disease
</P>

 


<P ID="2">Date Published to Web: <TIMEX TYPE="DATE">12/26/2003</TIMEX>
</P>



<P ID="3">1-Column 
> 
> 
> 
> 
>
</P>



<P ID="4"><TIMEX TYPE="DATE">1985</TIMEX>
</P>

<P ID="5"><ENAMEX TYPE="ORGANIZATION">Bovine Spongiform Encephalophathy</ENAMEX> (<ENAMEX TYPE="ORGANIZATION">BSE</ENAMEX>), also known as mad cow disease, is first observed in the 
<ENAMEX TYPE="LOCATION">United Kingdom</ENAMEX>
 (
<ENAMEX TYPE="LOCATION">Great Britain</ENAMEX>
). The first related case of <ENAMEX TYPE="ORGANIZATION">BSE</ENAMEX> occurred in <TIMEX TYPE="DATE">February 1985</TIMEX>. "Cow 133" died after suffering head tremors.
</P>

<P ID="6"><TIMEX TYPE="DATE">November 1986</TIMEX>
</P>

<P ID="7">The first confirmed case of <ENAMEX TYPE="ORGANIZATION">BSE</ENAMEX> is identified in the 
<ENAMEX TYPE="LOCATION">United Kingdom</ENAMEX>
.
</P>

<P ID="8"><TIMEX TYPE="DATE">July 1998</TIMEX>
</P>

<P ID="9">Government officials ban the inclusion of meat and bone from ruminant (grazing) animals into cattle feed. Ruminant animals are believed to carry the prions that cause <ENAMEX TYPE="ORGANIZATION">BSE</ENAMEX>.
</P>

<P ID="10"><TIMEX TYPE="DATE">July 1989</TIMEX>
</P>

<P ID="11">The <ENAMEX TYPE="ORGANIZATION">United States Department of Agriculture</ENAMEX> bans the importation of ruminant animals from countries with confirmed <ENAMEX TYPE="ORGANIZATION">BSE</ENAMEX> cases.
</P>

<P ID="12"><TIMEX TYPE="DATE">May 1990</TIMEX>
</P>

<P ID="13"><ENAMEX TYPE="LOCATION">United Kingdom</ENAMEX>
 scientist Professor <ENAMEX TYPE="PERSON">Richard Lacey</ENAMEX> calls for the slaughter of all <ENAMEX TYPE="ORGANIZATION">BSE</ENAMEX> infected herds in the 
<ENAMEX TYPE="LOCATION">United Kingdom</ENAMEX>
. During the same period, the British agricultural minister declares that all beef products are completely safe to eat, even appearing on television in a commercial with his 4-year-old daughter eating a hamburger. 
</P> 


<P ID="14"><TIMEX TYPE="DATE">June 1990</TIMEX>
</P>

<P ID="15">Out of 10 million cattle in 
<ENAMEX TYPE="LOCATION">Great Britain</ENAMEX>
, more than 14,000 are confirmed to have <ENAMEX TYPE="ORGANIZATION">BSE</ENAMEX>.
</P>

<P ID="16"><TIMEX TYPE="DATE">December 1991</TIMEX>
</P>

<P ID="17"><ENAMEX TYPE="ORGANIZATION">United States Department of Agriculture</ENAMEX> bans at-risk by products of ruminant origin from countries with <ENAMEX TYPE="ORGANIZATION">BSE</ENAMEX>.
</P>

<P ID="18"><TIMEX TYPE="DATE">1993</TIMEX>
</P>

<P ID="19">The United States Mad Cow Disease Surveillance Program expands to include examination of brain tissue from downed cows.
</P>

<P ID="20"><TIMEX TYPE="DATE">January 1993</TIMEX>
</P>

<P ID="21">The <ENAMEX TYPE="ORGANIZATION">BSE</ENAMEX> epidemic reaches epic proportions in the 
<ENAMEX TYPE="LOCATION">United Kingdom</ENAMEX>
. Mad cow disease at its peak during <TIMEX TYPE="DATE">this period</TIMEX> reached 1,000 new cases each week. 
<ENAMEX TYPE="LOCATION">United Kingdom</ENAMEX>
 officials brought that figure down to about 300 reported <ENAMEX TYPE="ORGANIZATION">BSE</ENAMEX> cases by <TIMEX TYPE="DATE">1996</TIMEX>.
</P>

<P ID="22">1986-1996
—More
</P>

<P ID="23">than 155,000 cases of <ENAMEX TYPE="ORGANIZATION">BSE</ENAMEX> are identified in the 
<ENAMEX TYPE="LOCATION">United Kingdom</ENAMEX>
. The disease in the 
<ENAMEX TYPE="LOCATION">United Kingdom</ENAMEX>
 peaks between 1992-93 with a reported 100,000 confirmed cases.
</P>

<P ID="24"><TIMEX TYPE="DATE">May 21, 1995</TIMEX>
</P>

<P ID="25"><ENAMEX TYPE="PERSON">Stephen Churchill</ENAMEX>, 19, is the first known human death from <ENAMEX TYPE="ORGANIZATION">BSE</ENAMEX>. Three more 
<ENAMEX TYPE="LOCATION">United Kingdom</ENAMEX>
 residents die that year from the disease.
</P>  


<P ID="26"><TIMEX TYPE="DATE">March 20, 1996</TIMEX>
</P>

<P ID="27">British government officials confirm the suspicion of many scientists, announcing a link between <ENAMEX TYPE="ORGANIZATION">BSE</ENAMEX> and the Cruetzfeldt-Jacob disease, which is a human form of <ENAMEX TYPE="ORGANIZATION">BSE</ENAMEX>.
</P>

<P ID="28"><TIMEX TYPE="DATE">Aug. 4, 1997</TIMEX>
</P>

<P ID="29">The <ENAMEX TYPE="ORGANIZATION">United States Food and Drug Administration</ENAMEX> establishes regulations prohibiting the feeding of most mammalian proteins to ruminants.
</P>

<P ID="30"><TIMEX TYPE="DATE">February 2000</TIMEX>
</P>

<P ID="31">A mother carrying the Cruetzfeldt-Jakob disease gives birth to a daughter in the 
<ENAMEX TYPE="LOCATION">United Kingdom</ENAMEX>
, who also tests positive for the disease.
</P>

<P ID="32"><TIMEX TYPE="DATE">July 2000</TIMEX>
</P>

<P ID="33"><ENAMEX TYPE="LOCATION">United States</ENAMEX>
 officials declare an emergency situation after four sheep in 
<ENAMEX TYPE="LOCATION">Vermont</ENAMEX>
 tested positive for <ENAMEX TYPE="ORGANIZATION">BSE</ENAMEX> related symptoms. The cause of the outbreak was eventually traced back to feed purchased from 
<ENAMEX TYPE="LOCATION">Belgium</ENAMEX>
.
</P>

<P ID="34"><TIMEX TYPE="DATE">Nov. 23, 2000</TIMEX>
</P>

<P ID="35">The first case of <ENAMEX TYPE="ORGANIZATION">BSE</ENAMEX> is confirmed in 
<ENAMEX TYPE="LOCATION">Spain</ENAMEX>
.
</P>

<P ID="36"><TIMEX TYPE="DATE">Nov. 24, 2000</TIMEX>
</P>

<P ID="37">The first reported case of <ENAMEX TYPE="ORGANIZATION">BSE</ENAMEX> is confirmed in 
<ENAMEX TYPE="LOCATION">Germany</ENAMEX>
 after the birth of two calves.
</P>

<P ID="38"><TIMEX TYPE="DATE">1993</TIMEX>
</P>

<P ID="39"><ENAMEX TYPE="ORGANIZATION">BSE</ENAMEX> invades 
<ENAMEX TYPE="LOCATION">Canada</ENAMEX>
. The first reported case of mad cow disease in 
<ENAMEX TYPE="LOCATION">Canada</ENAMEX>
 occurred in 
<ENAMEX TYPE="PERSON">Red Deer</ENAMEX>
, 
<ENAMEX TYPE="LOCATION">Alberta</ENAMEX>
. The cow was imported from 
<ENAMEX TYPE="LOCATION">Great Britain</ENAMEX>
 in <TIMEX TYPE="DATE">1987</TIMEX>.
</P>
<P ID="40"><TIMEX TYPE="DATE">December 2002</TIMEX>
</P>

<P ID="41"><ENAMEX TYPE="LOCATION">United States</ENAMEX> government officials test tissue from a Mabton Holstein dairy cow and an <ENAMEX TYPE="LOCATION">Alderwood</ENAMEX> cow in <ENAMEX TYPE="LOCATION">Iowa</ENAMEX> after the downed animals are identified with potentially having <ENAMEX TYPE="ORGANIZATION">BSE</ENAMEX> at a rendering plant. The tissue is tested for mad cow disease. The results of the tissue test sampling in <ENAMEX TYPE="LOCATION">Iowa</ENAMEX> prompts the samples to be sent to the <ENAMEX TYPE="LOCATION">United Kingdom</ENAMEX> for <ENAMEX TYPE="ORGANIZATION">BSE</ENAMEX> confirmation.
</P>
<P ID="42"><TIMEX TYPE="DATE">Dec. 25, 2002</TIMEX>
</P>

<P ID="43">A British laboratory confirms that the Mabton Holstein suspected of contracting <ENAMEX TYPE="ORGANIZATION">BSE</ENAMEX> is infected with the deadly disease.
</P>


<P ID="44"><TIMEX TYPE="DATE">Oct. 29, 2003</TIMEX>
</P>

<P ID="45">A 21-month-old bull is killed in <ENAMEX TYPE="LOCATION">Japan</ENAMEX> after testing positive for <ENAMEX TYPE="ORGANIZATION">BSE</ENAMEX>. It is the ninth cow killed in <ENAMEX TYPE="LOCATION">Japan</ENAMEX> since the illness was discovered in <TIMEX TYPE="DATE">2001</TIMEX>.
</P>









 










<P ID="46">Webmaster
</P><P ID="47">  Copyright 
<ENAMEX TYPE="ORGANIZATION">Hawk Press Inc.</ENAMEX>
, 
</P>




